### ISSUE TITLE
SSL deployment failing

### ISSUE THREAD

**Issue by chris-garrett** [arunoda/meteor-up-legacy#1097]
Hiya, 

I followed the instructions for deploying with ssl. My config looks like: 

```
  "ssl": {
    "certificate": "./private/ssl/bundle.crt",
    "key": "./private/ssl/private.key",
    "port": 443
  }
```

When deploying mupx shows no errors but the server is not accessible by https. A little more investigating shows that nginx is is throwing this error and the container is in a loop constantly restarting. 

```
nginx: [emerg] PEM_read_bio_X509_AUX("/bundle.crt") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
```

I tested the keys in nginx locally so I'm fairly confident that's not the issue. 

More digging around and I find where the volumes are pointing to and this is what I find:

```
drwxr-xr-x 2 root   root   4.0K Jul 30 21:42 bundle.crt/
-rw-rw-r-- 1 ubuntu ubuntu  224 Jul 30 21:42 env.list
drwxr-xr-x 2 root   root   4.0K Jul 30 21:42 private.key/
```

I suspect these are supposed to be files not directories?

Setup:
- mupx 1.5.3
- dev machine: ubuntu 16
- prod machine: ec2 instance, ubuntu 14.

**Comment by chris-garrett** [comment]
I copied my keys up to the ec2 instance and tested using the same image and confirmed the keys are working:

```
docker run \
        -d \
        --restart=always \
        --volume=/opt/$APPNAME/config/mybundle.crt:/bundle.crt \
        --volume=/opt/$APPNAME/config/myprivate.key:/private.key \
        --link=$APPNAME:backend \
        --publish=443:443 \
        --name=nx \
        meteorhacks/mup-frontend-server /start.sh
```

**Comment by yourse1f-yourorg** [comment]
@chris-garrett 

As far as I can tell there is NO alternative to the naming of those two files.  You **have to use** `/opt/${APPNAME}/config}/bundle.crt` and `/opt/${APPNAME}/config/private.key`.

My solution was this : 

##### preSetup.sh

```
#!/bin/bash
#
echo "IN  : >>>>>>>>>>>>>>> Setting up private elements <<<<<<<<<<<<<<<";

MUP_CONFIG_DIR="/opt/${APPNAME}/config";
mkdir -p ${MUP_CONFIG_DIR};

cp /home/${HOST_USER_NAME}/.ssh/${HOST_SERVER_NAME}_bundle.crt ${MUP_CONFIG_DIR}/bundle.crt
openssl rsa -passin file:/home/${HOST_USER_NAME}/.ssh/${HOST_SERVER_NAME}.pkp -in /home/${HOST_USER_NAME}/.ssh/${HOST_SERVER_NAME}.key -out ${MUP_CONFIG_DIR}/private.key 

echo "OUT : >>>>>>>>>>>>>>>   Set up private elements   <<<<<<<<<<<<<<<";
```

I run that with an RPC like this : 

```
source ~/.profile
ssh ${HOST_USER_NAME}@${HOST_SERVER_NAME} 'bash -s' < preSetup.sh
```

Then I can do my `mup setup`.

Obviously, the two files need to be present already on the server.  As you can see, I stick them in the .ssh directory of the 'mup' user.  I am much more comfortable with that, than giving them to the Continuous Integration cloud service I use: circleci.com.  Not because I don't trust them, but because I am using their free FOSS account in which nearly everything is visible to the public.
