### ISSUE TITLE
Is there a way to restart my meteor app daily?

### ISSUE THREAD

**Issue by seiyria** [arunoda/meteor-up-legacy#160]
It would be nice, because I have some performance problems that are a bit difficult to diagnose, so I'd like to restart the site every day at a certain time, for now.

**Comment by arunoda** [comment]
You can write a cron script inside your server and do

stop meteor && start meteor

If you've set a name to your app, use it instead of meteor.

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by seiyria** [comment]
Thanks!
