### ISSUE TITLE
git based workflow

### ISSUE THREAD

**Issue by benjiqq** [arunoda/meteor-up-legacy#185]
mup deploys using meteor bundle/deploy feature. I'm wondering whether for a more complex application, it would not be better to build on a git workflow, i.e. a server has a git repo and pulls changes or reacts to git hook events. Shipping the entire application instead of just code to run the application could be sub-optimal where the workflow includes tools outside meteor, such as a backend in a different language. So instead I'm thinking about building on mup to use a git pull /hook based workflow. That way one can have continuous integration, automated testing, etc.

**Comment by gustoase** [comment]
+1.
And with the possibility of not all resources deploit and only modified..

**Comment by benjiqq** [comment]
I don't know the details of Meteor deploy. I basically want all my dependencies in files, so to be able to reproduce an environment. As I understand people use node-forever and run the bundle/main.js for that.

For githooks there is this: https://github.com/mcwhittemore/node-hooks/

This could be a separate repo and merged upstream later, depending on goals of mup. Comments and ideas appreciated.

Other somewhat related projects are [passenger](https://github.com/phusion/passenger), the commercial app [codeship.io](http://codeship.io) and [docker.io](http://docker.io).

**Comment by arunoda** [comment]
Yes. This is a good suggestion. 
Our focus on mup is to build the meteor bundle and use that to deploy. 

Implementing git based deployment is great but not so trivial if we need to work with multiple servers. 

With that we are building the app on the deploy server. Then it's possible to have building issues which don't exists when building locally. 

So, for now we don't go for this. But may be later someday. 

## CI / CD

We use mup with codeship and it works pretty great. We don't need git based deployment for that. 
And when doing so, uploading the whole bundle is not an issue since we have very high bandwidth.
