### ISSUE TITLE
Deploy From Git Repository

### ISSUE THREAD

**Issue by joncursi** [arunoda/meteor-up-legacy#315]
This is more of a feature request than an issue, so feel free to close. But I think it would be great to be able to specify a git URL inside `mup.json` rather than having to deploy based on local code.

https://github.com/arunoda/meteor-up/blob/master/example/mup.json#L29

Thoughts?

**Comment by joaopiopedreira** [comment]
- 1 for this

**Comment by MaazAli** [comment]
There was a PR to add this functionality but @arunoda detailed why it wasn't the scope of this plugin: https://github.com/arunoda/meteor-up/pull/212

---

I've looked at this a bit. I think it's not a good idea to have something like this in meteor-up. I'm sorry, I didn't say this earlier and you've spent a lot of time and energy on this. Here's the reason behind why I am saying I'm not going to merge this.

This make mup a bit complex and hard to manage (now we've don't have a testing suite and it's hard to test manually with a lot of functionalities)
Now, we need to address a new set of issues. We are already receiving a lot of issues per week. So this makes it more harder to manage issues. Some might argue mup is buggy because some unrelated issue in users git setup.
I think this can be done outside of the mup. You can do all the git stuff as another tool. After that you can invoke mup.

**Comment by joncursi** [comment]
Thanks @MaazAli
