### ISSUE TITLE
Mupx deploy error

### ISSUE THREAD

**Issue by shividhar** [arunoda/meteor-up-legacy#588]
I get the following error when I try to deploy my app `error: npm-container is not compatible with architecture 'os.linux.x86_64'`. The DEBUG command isn't helpful either.

**Comment by pjbrow** [comment]
+1 on Digital Ocean

**Comment by crenwick** [comment]
Also running into the same issue.

**Comment by MasterJames** [comment]
Maybe something in this thread will help...
https://github.com/meteorhacks/npm/issues/40

**Comment by arunoda** [comment]
Yes exactly. This is when you've a binary NPM module. Meteor does not allow to do that via `meteorhacks:npm`. You need to wrap it as a Meteor package and build binaries. 
@MasterJames's link has all the info.

Also, someone else may also got this issue. So check atmosphere as well.

**Comment by pjbrow** [comment]
Would this explain why MUP is working but not MUPX?

I am not having this issue with MUP, but I am having this issue with MUPX.

**Comment by arunoda** [comment]
Yes. Mup try to build them on the server. That's leads a lot of runtime
issues.

Yeah! I'd like to see this on README. Can you send me a PR?

**Comment by pjbrow** [comment]
To be clear: the runtime issues you're talking about are for MUPX, not MUP (as stated), right?

**Comment by arunoda** [comment]
Nope. It's for mup. This is not the runtime issue I mentioned.

While we are building npm modulus on the server in mup, it introduced a lot
of issues because of the environment in the server. Mup has no control over
that. That's why we removed it from mupx.

Meteor deploy also act like mupx. That was another reason for this choice.

**Comment by pjbrow** [comment]
Ok, I see.  I just (wrongly) assumed that MUPX had more features rather than less.  :)

I'll get a pull request done.

**Comment by hems** [comment]
i don't understand why this issue is closed if there is no clear solution stated anywhere... i mean, i get the error "error: this app is not compatible with architecture 'os.linux.x86_64'" without any details on why it's not compatible.. how i'm supposed to fix that? :'(

that didn't happen when using mup...
