### ISSUE TITLE
Mup deploy taking forever

### ISSUE THREAD

**Issue by hassanasad** [arunoda/meteor-up-legacy#594]
After installing a clean version of ubuntu 14.04 x64 on my digital ocean instance (2GB RAM) i ran

`mup setup`

It installed everything successfully in few minutes. Then i ran

`mup deploy`

Its taking a lot of time on the `Invoking deployment process`. Is that normal? Its been more than half hour.

**Comment by hassanasad** [comment]
I am not getting any errors when using `mup logs -f`

Also on the server, i dont have the 'app' folder here `/opt/<appname>/` just tmp and config

**Comment by MasterJames** [comment]
There's a few threads about that you can google that might help...
https://github.com/arunoda/meteor-up/issues/572
We went over a few of them like waitTime etc.
Also I think you said you're using DigitalOcean so maybe this will help...
https://www.digitalocean.com/community/tutorials/how-to-deploy-a-meteor-js-application-on-ubuntu-14-04-with-nginx

I'm still wondering if you're using mupx instead of mup?
Another long and older thread that might be fruitful.
https://github.com/arunoda/meteor-up/issues/125

I guess better logging after "Invoking deployment process" is a good idea.

**Comment by hassanasad** [comment]
Hi James,

Thanks for helping me. Really appreciate it.

Yes i am using a 2GB instance from Digital Ocean. The article you mentioned looks interesting. Gives deep understanding of how to set it up manually.

However, i am afraid next deployments will be harder (in comparison to mup) :'(

I am using mup and not mupx. I will test with mupx now :)

**Comment by MasterJames** [comment]
Verbose Output
If you need to see the output of mupx (to see more precisely where it's failing or hanging, for example), run it like so:

DEBUG=\* mupx <command>
where <command> is one of the mupx commands such as setup, deploy, etc.

**Comment by hassanasad** [comment]
Ah Thanks James.

I just made a new droplet and now it _worked_ finally with `DEBUG=* mupx setup` and `DEBUG=* mupx deploy` command.

You can imagine the joy i feel :')

**Comment by MasterJames** [comment]
Excellent time to close another one.
Happy computing!
