### ISSUE TITLE
Information on how to connect to db on server

### ISSUE THREAD

**Issue by BasilPH** [arunoda/meteor-up-legacy#64]
I used meteor up to deploy my meteor app on a server, and it works flawlessly.
I would now like to connect to this database on the server, but for this I need to know the mongodb url. I can't figure out what port, username and password to use. Any ideas on how I could get those?

**Comment by arunoda** [comment]
Actually, you can't login into the mongo from the outside of the server.
You need to login to the server and do it.
There is no authentication and that's why Mup does not allow login from
outside.

Once you logged in, you can connect to the db with "mongo meteor"

---

Arunoda Susiripala
I curate Meteor Weekly - Check it
out!http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by BasilPH** [comment]
Thanks, that makes sense. I think this would be nice information to have in the README. Should I make you a pull request for this?

**Comment by arunoda** [comment]
Sure. Please do it :)

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
 http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
