### ISSUE TITLE
MUP/MUPX with compose.io Beta MongoDB+ cluster?

### ISSUE THREAD

**Issue by guilcorp** [arunoda/meteor-up-legacy#724]
Does any one know or try to use the compose MongoDB+ hosting?

No usual replicatset url on admin panel...

MongoDB url are like this one:

`mongodb://<user>:<password>@aws-eu-west-1-portal.1.dblayer.com:10813,aws-eu-west-1-portal.0.dblayer.com:10684/database?ssl=true`

I got verifying deployment error, mupx can't connect to the db.

Is there a workaround or will it not working at all?

Thanks!

**Comment by MasterJames** [comment]
You jave confirmation the Mongo database is running?  Can you access the machine otherwise? 
Are you using mup or mupx?

**Comment by mirstan** [comment]
@guilcorp, make sure that you've tested the connection with mongo command line util that has SSL support:
https://www.compose.io/articles/going-ssl-with-compose-mongodb-plus/

Otherwise, reach out to their support, as they are quite responsive.

I ended up not using it because they don't support oplog tailing on this setup.

**Comment by guilcorp** [comment]
Indeed.

I contacted them (quick reply) and they give me the replica set name. But told me that Meteor is not compatible with MongoDB+.
