### ISSUE TITLE
Updating code after deployment

### ISSUE THREAD

**Issue by jzhangtech** [arunoda/meteor-up-legacy#754]
Is there anyway to update the app/code after it's deployed?
I assume you just had to redeploy it, but that didn't change anything.

**Comment by MasterJames** [comment]
The database is preserved across deployments.
Running setup will overwrite it. I made a PR to mupx with extra mongo tools to dump and restore, and clear locks that can jam restart etc. (I fear it doesn't seem like any more extensive PRs will be merged any time soon). Anyway in mupx the Mongo container mounts a local volume I recall it's (/var/lib/mongodb/) and so that can be confusing and is worth pointing out to people. It's briefly mentioned somewhere in the documentation that it persist intentionally.
