### ISSUE TITLE
Archiving fails using React 0.14.4

### ISSUE THREAD

**Issue by natecox** [arunoda/meteor-up-legacy#812]
When using the current version of React from atmosphere `mup deploy` (and `mupx deploy`) will fail due to an archiving error. The issue goes away with a reversion to react 0.14.3.

See details here: https://forums.meteor.com/t/mupx-archiving-failed-enoent/15281/4

**Comment by rogchap** [comment]
:+1:

**Comment by Siyfion** [comment]
Yup, this is a weird one, but I can confirm that I am suffering from this also..

**Comment by TedAvery** [comment]
+1

**Comment by john-guerra** [comment]
+1

A workaround:

From https://forums.meteor.com/t/mupx-archiving-failed-enoent/15281/10 the problem is the the latest version of react, and falling back to 0.14.3 fixes the problem. For doing so edit your 

PROJECTFOLDER/.meteor/packages

and add:

react-runtime@=0.14.3
react-runtime-dev@=0.14.3
react-runtime-prod@=0.14.3

then run meteor update, and try the mup deploy again. This worked for me

**Comment by gitTerebi** [comment]
Assuming you mean
meteor update
mup deploy

**Comment by john-guerra** [comment]
Yep, changing my previous comment

**Comment by Batistleman** [comment]
instead of reverting, how can I help to solve this issue?

**Comment by Batistleman** [comment]
bumping the archiver version to 0.21.x does not seem to fix the issue...

**Comment by sergical** [comment]
+1

**Comment by gitTerebi** [comment]
+1

**Comment by dubielzyk** [comment]
+1

**Comment by perminder-klair** [comment]
+1

**Comment by stolinski** [comment]
+1

**Comment by perminder-klair** [comment]
fixed it for now by downgrading React, seems more like react issue then MUP.

**Comment by aaronsmulktis** [comment]
+1

**Comment by aaronsmulktis** [comment]
I'm having this issue _with_ react-runtime 0.14.3.

react-meteor-data              0.2.4*
react-runtime                      0.14.3*
react-template-helper         0.2.4*

**Comment by Weijtmans** [comment]
+1

**Comment by jtolla** [comment]
+1

**Comment by ghost** [comment]
I've also had the same issue with react 0.14.3.

**Comment by DClark5218** [comment]
+1

**Comment by yourcontainer** [comment]
How to fixed:
add

```
react-runtime@=0.14.3
react-runtime-dev@=0.14.3
react-runtime-prod@=0.14.3
```

to you packges file, then run
`meteor update --allow-incompatible-update`
then you can make deploy you app without any errors
`mupx deploy`

**Comment by Batistleman** [comment]
@yourcontainer I agree that it works, but it's more like a workaround than a fix...

**Comment by gitTerebi** [comment]
Is this never going to be fixed? Just waiting for next version of meteor 1.3?

**Comment by dubielzyk** [comment]
I just went for Meteor Galaxy and I'm extremely glad I did.

**Comment by natecox** [comment]
Galaxy is a cool idea, but it's wildly too expensive for a small team or for client work.

**Comment by sudhin** [comment]
Instead of downgrading react , the following change worked for me :

add the following to the archiveIt function in build.js file of your mup installation ("/usr/local/lib/node_modules/mup/lib/build.js" for me)  ... 

```
var esprimaFolder = sourceDir+'/programs/server/npm/react-runtime-prod/node_modules/react/node_modules/envify/node_modules/jstransform/node_modules/esprima-fb/';
  if(fs.existsSync(esprimaFolder+'#README.md#')){
    fs.renameSync(esprimaFolder+'#README.md#',esprimaFolder+'.#README.md');
}
```

The complete file highlighting where to add the code...[gist](https://gist.github.com/sudhin/fdbf0bdcaaaaf7d26e64)

**Comment by nikos** [comment]
thanks @sudhin this fixed it for me (when using nvm the path was for me:  `~/.nvm/versions/node/v5.5.0/lib/node_modules/mup/lib/build.js`)

**Comment by nickredmark** [comment]
+1

**Comment by krtrice** [comment]
+1

**Comment by jasongrishkoff** [comment]
This seems to have become an issue for me with the upgrade to 1.3 (which is weird, because using beta.16 it was working fine).

=> Archiving failed: ENOENT, stat '/tmp/f6e6bc0c-cdbb-4737-901c-299a8b2c9874/bundle/programs/server/npm/node_modules/.bin/webpack'

I've tried rolling back versions to 0.14.3 as above, but with no luck (this used to work for me).  One potential issue is that when I upgraded to 1.3, it prompted me to run the following:

`meteor npm install --save react react-dom react-addons-transition-group react-addons-css-transition-group react-addons-linked-state-mixin react-addons-create-fragment react-addons-update react-addons-pure-render-mixin react-addons-test-utils react-addons-perf`

I'm wondering if that might be causing the issue now...

**Comment by jasongrishkoff** [comment]
Okay, I've been stuck on this for ~5 hours now, but I think the following just worked:

1) Remove all local files for my app. This unwittingly reset my local mongo database?
`rm -rf <path to app source files>/.meteor/local/`

2) Rebuild Meteor, at which point I was prompted with an error about react not being installed. The error suggested I run the below code, to which I added the @=0.14.3 portion.  And to my surprise, it deployed!
`meteor npm install --save react react-addons-pure-render-mixin@=0.14.3 load-script`

If I were to guess, clearing my local folder got rid of the "meteor npm install" for react that I'd mentioned in my previous comment.  At that point I had the opportunity to reinstall it, but this time using the @=0.14.3 clause.
