### ISSUE TITLE
SLL Support

### ISSUE THREAD

**Issue by trevordowdle** [arunoda/meteor-up-legacy#817]
I am currently deploying to an Amazon Web Services umbuntu server and am trying to implement SSL.

I generated a Certificate and added it to a load balancer on Amazon.  When I go to the SSL version of the page it validates however the page is left blank.  So i'm looking for some additional help or another approach.

I just noticed that MUP has SSL support.  Should I remove the CSR certificate from Amazons load balancer and use it strictly through MUP.  (By following the stud SSL terminator documentation)  Or do they need to work in tandem?

Please advise,

Thanks

**Comment by markshust** [comment]
If you use AWS's LB SSL, you can completely disable/not use SSL in mup config, because the LB handles all of the SSL termination. So it accepts SSL, terminates it, which converts everything to standard non-encrypted data (on port 80).

I would think AWS's SSL would be more efficient as it's on the network load balancer. I believe it depends on your security requirements and when exactly you want to terminate the SSL.

**Comment by trevordowdle** [comment]
Thank you for the feedback Mark.  I got it to work using MUP whereas I was having a little trouble with AWS.  But i'll keep that tip in mind and see if I can't go the more efficient route.

Thank you
