### ISSUE TITLE
Development Version ?

### ISSUE THREAD

**Issue by Obiwarn** [arunoda/meteor-up-legacy#876]
mup readme says it is outdated and links to mupx

but there it says "(Development Version)"

which is the stable git link?

**Comment by MasterJames** [comment]
Mupx uses docker and is being porter over to kadirahq while the orignal mup does things differently and is prefer by some.
I think they are saying its now or soon okay to start trying the new kadirahq one first (but it's still beta testing) or if it doesnt work easily come back to this arunoda Mupx version which is the development branch of mup.
Only the kadirahq one is accepting PRs in the future as these are depreciated.
Anyway safest bet is to use mupx from arunoda, but its probably worth trying the kadirahq one just to see if it works for you already despite still being ported or possible it's safely in beta test mode now. If you try it please let me/us know if it'll work for you & others now,  thanks.

**Comment by Obiwarn** [comment]
um. i don't really understood. 
my problem is:
mup readme says mupx is stable
mupx readme says it is beta

**Comment by MasterJames** [comment]
Well mupx is the most "effective", "stable" is such a strong and deterministic word.
Mupx was radically different it fixed a lot of problems thanks to docker. Still others liked Mup as they couldn't handle docker as easily in the past.
Mup has a need to be updated but won't for instance with Meteor 1.2 you need node 0.10.40 but the default of 0.10.36 was good for meteor 1.1. A simple change but not here ... as mentioned its porting to kadirahq. So to call it stable is wrong as it won't really work but if you change the value presto.
Anyway I recommend mupx from here for now.

Your point is well taken its not something I can change.
What should it say in mupx now you understand the situation? The plan I think was to depreciate to kadirahq version but someone posted a PR last week and I explained kadirahq port and he suggested it be marked depreciated. For now it points to the development mupx branch and that Readme wasn't updated so sorry for any confusion.

**Comment by BudgieInWA** [comment]
Am I right in my understanding as follows?
- The arunoda master branch ("mup") was stable (for Meteor 1.1) but is no longer receiving updates.
- The arunoda mupx branch ("mupx") is a rewrite of mup using docker, but is not yet stable.
- The kadirahq's mup is a fork of arunoda mupx intended to replace it.

If so, the mup README should explain that it is stable for Meteor 1.1 and doesn't work for newer versions. It should explain that the only option for newer version of Meteor is mupx and it should link to prefered mupx fork.

The arunoda mupx README should explain how stable it is. It should point out that mup might work better for Meteor 1.1.

And for god's sake, make it clear in the README of each of the mupx forks which one should be used by end users, (or which one should be used under which circumstances if they have differences). Then make it clear where development is happening; are they both being maintained by separate devs, or has the kadirahq fork replaced the arunoda fork? If the community doesn't know **find out**.

---

You mention that

> "stable" is such a strong and deterministic word

which is true. **Meteor Up promises _Production Quality Meteor Deployments_, so we search for the stable version.** If my understanding is correct, then there is no stable (aka "production ready") version for Meteor >1.1 and the docs should be clear about this. It might not sound good to say that Meteor Up cannot support "Production Quality Meteor Deployments" at this time, but it is honest and is important for framing the community's discussion around Meteor deployment and Meteor Up.

**Comment by MasterJames** [comment]
I completely agree with you very confusing. 
My help here is unofficial and volunteered to free up the devs to do their excellent work.
The only thing I see missing is something in mupx Readme. "USE THIS ONE"
Stable in this context means they'really not tinkering and changing stuff like the kadirahq port it's more unpredictable then stabilized. 
Normally stable to me means no bugs/crashes or something akin to production ready.
It's a free tool I would not expect anyone to make such a claim lightly so I don't think they want to claim that on any version.
Anyway look this one is a bit messed up in those regards, but soon the kadirahq version will truly replace this version and it's improved yet radically different devices branch mupx which is the one to use still for now from what I can gather.
If you really want to get them to change the readme files here you'll have to AT them.
Personally I would try the new one if this one is lacking any features you want otherwise the mupx here is pretty good for most people. Stable?  More not going to change likely even the ReadMEs. Deployment Ready?  I'd say they are all just good guidelines and free helpers to get someone started. When/If you need production Ready scalability probably Galaxy is your best bet.

Thanks for using Meteor Up and sorry for the confusion.

So my advice...
Just try mupx. Don't worry about the ReadMes. 
If you have problems here that aren't already adressed issues your welcome to post them for some help (I'm kind of the guy helping here) but I would start using kadirahq it's an improvement and the developers are there to help (not here in the quickly depreciating versions).

Further (my observation and opinion) I'll say things change so fast now days you really need to do testing and have team members dedicated to staying on top of packages and helping with PRs etc. You decide if it's stable enough for you. You'll find out if it's production ready the hard way and adjust. (Always invite scale gradually for this reason the big guys do so should you so don't blow your marketing budget in one go.) You'll get to integrate and define new features as they become available. Breakage can usually be fixed easily because the devs avoid it and minimize the problems with depreciate warnings help etc. It's not as if you should drop some update to production without testing anyway. Then you get help if needed.
It's really your applications that are the bottle neck here. Is meteor stable? Is it scalable production ready? That really probably depends more on what you'really doing with it and how.
I'm going to recommend you start following ApolloStack Apollo by Meteor. it's next. will you wait for production ready is that a moment that is definable for everybody? No its relative to each situation.

**Comment by BudgieInWA** [comment]
Thanks James for your time helping to clear this up. Despite my frustrated tone earlier, I do appreciate your replies. I do suspect that in general it would be worth your time distilling your knowledge on these subjects into notes that can go into the READMEs to save future users from having to read pages of comments.

The READMEs have since been updated and the situation is more clear, so I think this issue can be closed. Thanks again.
