### ISSUE TITLE
mupx: Server unreachable on AWS every couple of weeks

### ISSUE THREAD

**Issue by derwaldgeist** [arunoda/meteor-up-legacy#898]
I am facing a strange phenomenon on my AWS instance.

Every two to three weeks, the server is not reachable anymore, neither via HTTP nor via SSH. In the EC2 console, the instance is marked as running, with all statuses set to OK. But still, the server won't respond to any request anymore. This does not depend on the location from which I am trying to access it (office or mobile network).

If I look at the time-point where the server gets down on Kadira, I can see that everything ran normal, with all performance values far below criticality (there's not much traffic so far on the machine), until suddenly all measures fall down to zero.

The only way to recover the instance is to stop and restart it.

I am using a t2.micro instance with the standard `Ubuntu Server 14.04 LTS (HVM)` image provided by Amazon's free tier. The only additional software I had installed besides Meteor is the `letsencrypt` tool to get an SSL certificate for the machine. All the rest is "bare-bone" Ubuntu.

Do you have any clues what happens here, or how I could analyze what's going on?

Thanks in advance for any help,
Tom

PS: I am using the mupx branch of mup.

**Comment by MasterJames** [comment]
The idea of seeing if it lasts longer with an instance with more RAM comes to mind from your mentioning the micro image. Of course if spending more for no great reason (meaning doesn't make a difference or a poor trade off), isn't ideal it would reveal maybe a memory leak etc. So maybe your RAM can be monitored.
Still you say that doesn't seem to be a problem from the OKs maybe? 
Also try the new kadirahq port as that might also give you a different result. 
Having extra failover servers in a scalable design should also help. You could have a script see its actually not OK / responding to curl or what have you and that would trigger a restart while a second machine would take over while it's not responding in theory.

**Comment by derwaldgeist** [comment]
Hi @MasterJames, thanks for your quick reply. I am monitoring the RAM using Kadira, so I have a screenshot of the time-point between 7:00 and 9:00 where the problem occurred. As you can see in the image, memory usage was in fact significantly higher (~ 770 MB) before the incident than after I restarted the instance (~ 200 MB). Could be a memory leak. Is there a way to find out if this leak is provoked by the app or lies in the infrastructure (mupx, Docker)? And would a memory leak also explain why the server does not even react on SSH?

![kadiralog](https://cloud.githubusercontent.com/assets/3984535/13475463/5a0fb67c-e0c3-11e5-8ee0-0fc647f14226.png)

Regarding the kadirahq port: Is this safe for productive use already? Thought it was still in dev stage.

And yes, a failover server would definitely help. Is it easy to set-up this with mupx and meteor cluster?

**Comment by MasterJames** [comment]
Easy is relative to all the hard work you do to get it there I suppose. I would say with cluster one of the easiest and will get easier.
It's probably okay to see if its working for your use case. Probable as stable as mupx if not better regardless of official status the othere's is depreciated so i wold sTay for ward as possible (so only you can know). Mainly because you'll get more better help resolving possible issues. Stability in this case means changes so in this modern world you need to keep up whatever the cost. Refactoring on updates and running your own pre-deployment tests etc.

**Comment by MasterJames** [comment]
Anyway kadira is the perfect tool to find the leak or up your image size.

**Comment by derwaldgeist** [comment]
I see that the memory goes up in Kadira, but how do I find out the root cause? Is there any place in Kadira that shows which part of the software is actually using up all that memory? BTW: It seems as if I am not the only one with this problem:
http://stackoverflow.com/questions/35794893/how-to-find-a-memory-leak-in-meteor-app
Not sure if this is related, though. Could be a problem in our apps, of course.

**Comment by jpmermoz** [comment]
@derwaldgeist same issue here, did you ever find a solution for this problem?

**Comment by derwaldgeist** [comment]
There was a guy in the Meteor forums wh told me that this might be related to inefficient garbage collection in NodeJS. That would mean: It isn't a memory leak, but the memory of a micro instance (512mb) is lower than the trigger when Node actually performs its GC. He also described a solution which would require a patch of the mupx code. Since I did not want to touch this, I have filed a feature request for the mupx development version: https://github.com/kadirahq/meteor-up/issues/124. There you can also find links to the forum threads, including the aforementioned patch.

**Comment by derwaldgeist** [comment]
I'm closing this now in favor of https://github.com/kadirahq/meteor-up/issues/124

**Comment by jpmermoz** [comment]
@derwaldgeist thank you, we're getting this issue on a 1gb ec2 instance.. as a temp solution we forked meteord here (https://github.com/codingways/meteord) and added these flags

`node main.js --max_old_space_size=380 --gc_interval=100`

I'll report back in a few weeks

**Comment by derwaldgeist** [comment]
Thanks for sharing this!

**Comment by sahanDissanayake** [comment]
Looking forward to hear what happened with the new garbage collection :)

**Comment by jpmermoz** [comment]
@sahanDissanayake so far so good! after 10 days everything's working great.. i'll keep you guys updated

**Comment by derwaldgeist** [comment]
Sounds promising! One question about this: If you do a fork of mupx, how do you actually compile and use it? I know how to install it from npm, but I do not know how to build it myself.

**Comment by MasterJames** [comment]
Here is the script I dug up from when I did a PR for Backup & Restore of MongoDB.
I was using an Ubuntu VirtualBox VM on Windows and accessing a file mount.

```
cd /mnt/PersonalDevFolder/GitHub
rm mupx-1.5.3.tgz
tar cvzf mupx-1.5.3.tgz package/
npm uninstall -g mupx
npm install -g mupx-1.5.3.tgz
```

[Edit: I think you can just put "npm install" from the working folder and the package.json will do the rest.]
I suspect the 1.5.3 was because the latest one was likely 1.5.2 
I'm seeing 3.9.3 from npm -v mupx so?... you'll figure it out.
Maybe it doesn't matter about the file name version.
Right it's still this way in the mupx source 1.5.2
https://github.com/arunoda/meteor-up/blob/mupx/package.json

the folder "package" is a symbolic link (aka junction) to 
C:\PersonalDevFolder\GitHub\meteor-up

Note: it would be better to do work with the new version kadirahq/meteor-up if it doesn't already adress your issue.
