### ISSUE TITLE
Custom error pages mupx

### ISSUE THREAD

**Issue by JWo1F** [arunoda/meteor-up-legacy#919]
Hello, I want to set custom error pages for nginx. How can I do it? I need to edit a nginx config, but the one into docker container.

**Comment by MasterJames** [comment]
So you'll need to put something like this? 
Under server {
error_page 404 /custom_404.html;
        location = /custom_404.html {
                root /usr/share/nginx/html;
                internal;
        }

Until Meteor 1.3 officially is available you have to use nginx.
This file shows how mupx runs the docker image for the front end.
https://github.com/arunoda/meteor-up/blob/mupx/templates/linux/start.sh
It too runs a start.sh but from the frontend  docker image.
You would have to change the docker image somehow (custom PR or npm install hacks).
I think custom docker images is being added to the new port of this dev branch mupx at kadirahq's mup.
You might be able to pass those arguments from the configuration file for mupx under server?
Otherwise I would think about following the docker run command for the front end ssl to its volume mounts once you find a default file you should also be able to ssh or run a scp to overwrite said file but that would be better in hooks which is another feature only recently being added to the kadirahq port.
I hope this in general sets you on the path that is best for you. 
Maybe you try 1.3 and/or the kadirahq mup version or maybe you can just overwrite the right default file with scp or something simple and quick.
